create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.guestbook_entries (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 30),
  message text not null check (char_length(message) between 1 and 500),
  password_hash text not null,
  created_at timestamptz not null default now()
);

alter table public.guestbook_entries enable row level security;

revoke all on table public.guestbook_entries from anon, authenticated;
grant select (id, name, message, created_at)
  on table public.guestbook_entries to anon, authenticated;

drop policy if exists "Anyone can read guestbook entries" on public.guestbook_entries;
create policy "Anyone can read guestbook entries"
  on public.guestbook_entries
  for select
  to anon, authenticated
  using (true);

create or replace function public.create_guestbook_entry(
  entry_name text,
  entry_message text,
  entry_password text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id bigint;
  clean_name text := btrim(entry_name);
  clean_message text := btrim(entry_message);
begin
  if clean_name is null or char_length(clean_name) not between 1 and 30 then
    raise exception '이름은 1자 이상 30자 이하로 입력해 주세요.';
  end if;

  if clean_message is null or char_length(clean_message) not between 1 and 500 then
    raise exception '메시지는 1자 이상 500자 이하로 입력해 주세요.';
  end if;

  if entry_password is null or entry_password !~ '^[0-9]{4}$' then
    raise exception '삭제 비밀번호는 숫자 4자리로 입력해 주세요.';
  end if;

  insert into public.guestbook_entries (name, message, password_hash)
  values (clean_name, clean_message, extensions.crypt(entry_password, extensions.gen_salt('bf')))
  returning id into new_id;

  return new_id;
end;
$$;

create or replace function public.delete_guestbook_entry(
  entry_id bigint,
  entry_password text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  saved_hash text;
begin
  select password_hash
    into saved_hash
    from public.guestbook_entries
   where id = entry_id;

  if saved_hash is null
    or entry_password is null
    or extensions.crypt(entry_password, saved_hash) <> saved_hash then
    raise exception '비밀번호가 일치하지 않습니다.';
  end if;

  delete from public.guestbook_entries where id = entry_id;
  return true;
end;
$$;

revoke all on function public.create_guestbook_entry(text, text, text) from public;
revoke all on function public.delete_guestbook_entry(bigint, text) from public;

grant execute on function public.create_guestbook_entry(text, text, text)
  to anon, authenticated;
grant execute on function public.delete_guestbook_entry(bigint, text)
  to anon, authenticated;
